#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= spwhale_5modeb_volte.o sdio_cfg.o sprd_kp.o modem_entry.o pinmap-spwhale_5modeb_volte.o ldo_sleep.o sprd_bl.o
