#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= sp9838aea_fhd.o sdio_cfg.o sprd_kp.o modem_entry.o pinmap-sp9838aea_fhd.o ldo_sleep.o sprd_bl.o
