#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y	:= pinmap-sp8830.o ldo_sleep.o sdio_cfg.o sprd_kp.o sp7730sw.o modem_entry.o sprd_bl.o
